### ISSUE TITLE
Variable don't work

### ISSUE THREAD

**Issue by Cousclou** [vanshady/vidva#1]
The variable addition doesn't work, it remains stuck on the default IP

![Image](https://github.com/user-attachments/assets/1103275c-8143-474d-b608-eb4721c0475b)

my compose : 

```dockerfile
  vidva:
    image: vanshady/vidva:latest
    container_name: vidva
    environment:
      - PLEX_SERVER_URL=http://10.94.11.14:32400
      - PLEX_TOKEN=xxxxxxxxxxxxxxxxxxxx
      - PLEX_SERVER_ID=xxxxxxxxxxxxxxxxx
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - plexservices_arr_net
```

**Comment by vanshady** [comment]
Thank you for submitting this issue, there were some issues with docker setup. I've just updated the docker, please try update and let me know if it still doesn't work

**Comment by Cousclou** [comment]
It doesn't find any information.

![Image](https://github.com/user-attachments/assets/0dd8d8df-5981-40d2-8a2a-a1e9aaef4703)

**Comment by vanshady** [comment]
Could you double check your environment variables? Especially is that the way to access your plex docker ip? From my limited docker understandings, by default if plex docker is called “plex” it will be http://plex:32400
The errors are most likely just one of the env is wrong and it can’t connect.

**Comment by LionCityGaming** [comment]
Couldn't get it to work on my end either. Same issues. Checked envars, and they are as they should be.

**Comment by Cousclou** [comment]
> Could you double check your environment variables? Especially is that the way to access your plex docker ip? From my limited docker understandings, by default if plex docker is called “plex” it will be http://plex:32400 The errors are most likely just one of the env is wrong and it can’t connect.



It doesn't run on the same server as Plex, but it does have access to it.
So I don't think the service is properly picking up the variables

```yaml
  vidva:
    image: vanshady/vidva:latest
    container_name: vidva
    environment:
      - PLEX_SERVER_URL=http://10.94.11.14:32400
      - PLEX_TOKEN=xxxxxxxxxxxxxxxxxxxxxx
      - PLEX_SERVER_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - plexservices_arr_net
```
